# render.yaml
services:
  - type: web
    name: Property Management API
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: ""